server:
  port: 8099

spring:
  application:
    name: vote-service
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: true
  datasource:
    name: mysql
    type: com.zaxxer.hikari.HikariDataSource
    pool-name: vote-jdbcpool
    minimum-idle: 10
    maximum-pool-size: 100
    auto-commit: true
    idle-timeout: 30000
    max-lifetime: 1800000
    connection-timeout: 30000

mybatis:
  mapper-locations: classpath:sqlmap/*Mapper.xml
  type-aliases-package: cn.hui.dal.domain

weibo:
  appkey: 1452314314
  appsecret: 36d5be80e0cbb2bb243685f479795074
